# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b78371ff6dee07508d213722313b60007b6753c8deb776bf159479c9a3f76fb02064a1e60f9e743387157d5ff0b67c48b1d896e68c77401cb9d3f3b59a81288

test:
  secret_key_base: aa81e04785a95d6ced227b6df963428d2fd2c87f6cb105e86a81b6a009c11849c36ea6bc540238e2b687159a32cbc6109aaab20e9accba7e60743381d6e71630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
